language: node_js
node_js: "8"

install:
        - cd frontend
        - npm install

        - cd ../backend
        - make setup
script:
        # still inside the backend folder
        - make lint
        - make test

        - cd ../frontend
